version: 0.2

phases:
  pre_build:
    commands:
      # Docker Login
      #here 12345678 is the aws id you need to replace this with your aws id
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
      # ECR Login
      #- ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      #- aws ecr get-login-password --region ${AWS_REGION} | docker login -u AWS --password-stdin ${ECR_MAIN_URI}
      - aws ecr get-login-password --region ap-southeast-1 | docker login -u AWS --password-stdin 12345678.dkr.ecr.ap-southeast-1.amazonaws.com

      
  build:
    commands:
      - docker build -t website-project-1:latest .
  post_build:
    commands:
      # Docker push
      #- docker tag website-project-1:latest ${DOCKERHUB_USER}/website-project-1:latest
      #- docker push ${DOCKERHUB_USER}/website-project-1:latest
      #ECR Push
      #here 12345678 is the aws id you need to replace this with your aws id
      - docker tag website-project-1:latest 12345678.dkr.ecr.ap-southeast-1.amazonaws.com/website-12-feb:latest
      - docker push 12345678.dkr.ecr.ap-southeast-1.amazonaws.com/website-12-feb:latest
      
      # Generate image definitions file for ECS
      - printf '[{"name":"app2","imageUri":"%s"}]' 12345678.dkr.ecr.ap-southeast-1.amazonaws.com/website-12-feb:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
